### ISSUE TITLE
Version still show 1.3

### ISSUE THREAD

**Issue by MartinMajewski** [fenix-hub/unirest-gdscript#10]
Thanks for this great plugin! 

I'm starting out with Godot 4.0.1 and downloaded version 2.0 of your plugin. 

However, after import, it shows version 1.3, and in fact, inside the **plugin.cfg** file it is still set to 1.3.

Just a small cosmetic thing. 😎

**Comment by fenix-hub** [comment]
thanks for noticing, will be fixed in next update :)
