### ISSUE TITLE
Error loading addon with Godot 3.5

### ISSUE THREAD

**Issue by ConteZero** [fenix-hub/unirest-gdscript#9]
I've tried to test your addon with a clean project on Godot 3.5
It gives to me the following error:

```
E 0:00:00.216   _create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: nullptr
  <C++ Source>  modules/gdscript/gdscript.cpp:126 @ _create_instance()
  <Stack Trace> unirest.gd:7 @ _ready()
```

**Comment by fenix-hub** [comment]
Thank you, I'll check this right now

**Comment by fenix-hub** [comment]
I tried both using the Asset Library version and importing the addon from Github but I can't reproduce this issue (Godot Steam version and from the official download page).
What platform are you using? Where did you download the addon?

**Comment by ConteZero** [comment]
I've created a new project and imported from AssetLib, I'm using Linux (Opensuse Tumbleweed) and I get the error with the Opensuse Godot package and also using the version from Godot website.

This is the project:
[UnirestTest.zip](https://github.com/fenix-hub/unirest-gdscript/files/9452313/UnirestTest.zip)

**Comment by fenix-hub** [comment]
Just downloaded your project and run without any issue. Have you looked for similar errors for your platform on Godot's Github?

**Comment by ConteZero** [comment]
These two issues have a similar error:
https://github.com/godotengine/godot/issues/40817
https://github.com/godotengine/godot/issues/44676

**Comment by fenix-hub** [comment]
I've update the plugin with a smaller change, try to replace your version with the one from Github and let me know if you still get this error. Sadly I'm not able to reproduce it.

**Comment by ConteZero** [comment]
Unfortunately I get the same error.
I've changed some lines on `unirest.gd` and `configuration.gd` to avoid the .tres loading and now the error on addon load has gone.
But I get another error if I try to run the code in `test.gd`:

```
Invalid call. Nonexistent function 'as_dict' in base 'Reference (json_node.gd)'.
```
[UnirestTest.zip](https://github.com/fenix-hub/unirest-gdscript/files/9452832/UnirestTest.zip)

**Comment by fenix-hub** [comment]
`as_dict()` has been replaced with `get_dictionary()`, so you can use that function instead.
For the issue, I'll change the configuration code in order to prevent this

**Comment by ConteZero** [comment]
With `get_dictionary()` it works.
I still get the error:
`_create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: nullptr`
caused by .tres load in `empty_response.gd`

To fix this error I've changed two lines in `empty_response.gd`
```
extends Reference
class_name EmptyResponse

#var config: UnirestConfiguration = load("res://addons/unirest-gdscript/src/configuration/configuration.tres")

var props: Dictionary

var headers: Dictionary
var status: int
var error: UnirestError = null

func _init(headers: PoolStringArray, status: int, code: int, raw_body: PoolByteArray, props: Dictionary = {}) -> void:
	self.props = props
	if code > 0:
		error = UnirestError.new(
			{type = "HttpClient error", code = code}, 
			"HttpClient error is %s" % code
		)
	else:
		self.headers = UniOperations.dictionary_to_headers(headers)
		self.status = status
		if (status in [300, 500]):
			error = UnirestError.new(
				{status = status}, 
				"HTTP Status Code is %s" % status, raw_body.get_string_from_utf8()
			)

func get_headers() -> Dictionary:
	return headers

func get_status() -> int:
	return status

func _to_string() -> String:
#    return config.http_log_format.response \
	return Unirest.config().http_log_format.response \
	.format({
		host = UniOperations.resolve_host(get_meta("host")),
		date = Time.get_datetime_string_from_system(),
		headers = self.headers,
		status = self.status,
		ttr = get_meta("ttr", "?")
	   })
```

With these changes it works without errors.
Thanks for you support!

**Comment by fenix-hub** [comment]
Thank you for using this plugin :)
I'll figure out how to fix this. The issue using directly `Unirest` inside the plugin itself is that if the plugin is not enabled (even if not used), referencing `Unirest` which is a Singleton will result in errors anyway. Sadly that's how godot works for now.
